server:
  port: 8081
spring:
  jpa:
    hibernate.ddl-auto: validate
  datasource:
    url: ${URL}
    username: ${USERNAME}
    password: ${PASSWORD}
  liquibase:
    change-log: classpath:/db/changelog/2025_01_08_init_db.yaml
    enabled: true