name: CI/CD

on:
  push:
    branches:
      - '*'

env:
    GITHUB_USERNAME: ${{ github.actor }}
    GH_PACKAGES_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest



    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: '17'

      - name: Deploy using Environment Variables
        run: |
          mvn deploy \
            -DrepositoryId=github \
            -Durl=https://maven.pkg.github.com/YOUR_USERNAME/YOUR_REPOSITORY \
            -Dusername=$GITHUB_USERNAME \
            -Dpassword=$GH_PACKAGES_TOKEN

      - name: Run tests with JaCoCo
        run: mvn clean test jacoco:report

      - name: Upload to Coveralls
        run: mvn coveralls:report -DrepoToken=${{ secrets.COVERALLS_REPO_TOKEN }}

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}

      - name: Build Docker image
        run: docker build -t nastinkakrd/fd-notification-management:latest -f Dockerfile .

      - name: Push Docker image
        run: docker push nastinkakrd/fd-notification-management:latest
